name: aurenza
description: "AURENZA Flutter application"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^7.0.0
  http: ^0.13.6
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
